--
-- Global Lua definitions
------------------------------------------------------------
--
math.randomseed( os.time() * os.time() )
--
-- Random Permutation
function permute(tab, n, count)
    n = n or #tab
    for i = 1, count or n do
        local j = math.random(i, n)
        tab[i], tab[j] = tab[j], tab[i]
    end
    return tab
end
--
-- Squares
squares = {
    'Free Space',
    'Free Space',
    'Free Space',
    'Allergic to Cheese',
    'Born in another country',
    'Can salsa dance',
    'Can ballroom dance',
    'Can run 2 miles',
    'Can touch their toes',
    'Chews their fingernails',
    'Does not drink coffee',
    'Does not eat tomatoes',
    'Does not like meat',
    'Does not like chocolate',
    'Does not like pizza',
    'Flosses twice a day',
    'Has a Celine Dion CD',
    'Is left handed',
    'Has a twin',
    'Is afraid of spiders',
    'Is an only child',
    'Is younger than you',
    'Is older than you',
    'Loves flowers',
    'Has a dog',
    'Has a cat',
    'Is allergic to cats',
    'Is allergic to dogs',
    'Likes chick flicks',
    'Has ridden on an airplane',
    'Likes to eat french fries',
    'Is wearing something pink',
    'Has one sister',
    'Has one brother',
    'Wears glasses',
    'Has been to the zoo',
    'Packed their lunch today',
    'Likes to read',
    'Has four letters in their first name',
    'Has more than six letters in their first name',
    'Last name starts with an A',
    'Last name starts with an B',
    'Last name starts with an C',
    'Last name starts with an D',
    'Last name starts with an E',
    'Last name starts with an F',
    'Last name starts with an G',
    'Last name starts with an H',
    'Last name starts with an I',
    'Last name starts with an J',
    'Last name starts with an K',
    'Last name starts with an L',
    'Last name starts with an M',
    'Last name starts with an N',
    'Last name starts with an O',
    'Last name starts with an P',
    'Last name starts with an Q',
    'Last name starts with an R',
    'Last name starts with an S',
    'Last name starts with an T',
    'Last name starts with an U',
    'Last name starts with an V',
    'Last name starts with an W',
    'Last name starts with an X',
    'Last name starts with an Y',
    'Last name starts with an Z',
    'Has a computer at home',
    'Has gone bungee jumping',
    'Has a pet hamster',
    'Can count to 20 in Spanish',
    'Has never been out of the state',
    'Likes to skate',
    'Knows how to sew',
    'Never had any cavities',
    'Likes cats more than dogs',
    'Likes dogs more than cats',
    'Has been to Disneyland or Disneyworld',
    'Wore mismatched socks today',
    "Knows Smokey the Bear's middle name",
    'Is wearing tennis shoes',
    'Knows how to play guitar',
    'Can name all 50 state capitals',
    'Can name all 50 states',
    'Enjoys playing football',
    'Enjoys playing baseball',
    'Has more than one pet',
    'Is allergic to milk',
    'Owns more than 30 pairs of shoes',
    'Does not own a cell phone',
    'Has bigger hands than you',
    'Has smaller hands than you',
    'Cannot whistle',
    'Can whistle',
    'Knows how to rap',
    'Likes horror flicks',
    'Knows the lyrics of a Britney Spears song',
    'Has been to Canada',
    'Has been to Mexico',
    'Owns a bicycle',
    'Has ridden a motorcycle',
    'Has never been outside America',
    'Was born out of state',
    'Played on a football team',
    'Played on a baseball team',
    'Loves to bake cookies',
    'Likes very spicy food',
    'Loves Mathematics',
    'Loves Science',
    'Loves Physics',
    'Has won a pie eating contest',
    'Reads a book every week',
    'Loves walking in the rain',
    'Can stand on their hands',
    'Has never ridden on an airplane',
    'Cuts their own hair',
    'Has eyes of different colors',
    'Loves reading magazines',
    'Loves reading the newspaper',
    'Likes caviar',
    'Hates technology',
    'Likes wearing a tie',
    'Reads for pleasure',
    'Wears socks to bed',
    'Reads cookbooks',
    'Likes snow',
    'Does not like ice cream',
    'Knows a magic trick',
    'Has climbed a mountain',
    'Does not eat Turkey on Thanksgiving',
    'Can say the alphabet backwards',
    'Has more than five siblings',
    'Can name three marsupials',
    'Has as many siblings as you',
    'Likes yogurt',
    'Can wiggle their ears',
    'Prefers Pepsi over Coke',
    'Has worn braces',
    'Cannot swim',
    'Has a January Birthday',
    'Has a February Birthday',
    'Has a March Birthday',
    'Has an April Birthday',
    'Has a May Birthday',
    'Has a June Birthday',
    'Has a July Birthday',
    'Has an August Birthday',
    'Has a September Birthday',
    'Has an October Birthday',
    'Has a November Birthday',
    'Has a December Birthday',
    'Had a pet bird',
    'Has written to a politician',
    'Loves museums',
    'Has blue eyes',
    'Knows CPR',
    'Has caught a fish',
    'Is wearing shoes, not sneakers',
    'Has been to Los Angeles',
    'Has been to New York City',
    'Has been to Chicago',
    'Has been to Washington DC',
    "Has been to an O's game",
    "Has been to a Raven's game",
    "Is not a Raven's fan",
    "Is not an O's fan",
    'Is a first born child',
    'Is a second born child',
}
--
--
tab = {}
len = #squares
for i=1,len do
    tab[i] = i
end
tab = permute(tab,len,len)
count = 1
--
-- Print Random Square
function printRandom()
    tex.print( string.format("%s",squares[tab[count]]) )
    count=count + 1
end
--
-- End Of File
--
